version: '3.4'

services:
  projecttesting:
    image: projecttesting
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1
